#!/bin/bash -e

. /etc/sisyphus/functions
. /etc/sisyphus/config

Usage()
{
	[ "$1" = 0 ] || exec >&2
	cat <<EOF
sisyphus_check - check packages for acceptability for Sisyphus.

This program is free software, covered by the GNU General Public License.
sisyphus_check comes with ABSOLUTELY NO WARRANTY, see license for details.

Usage: $PROG [options] <directory>...

Valid options are:
EOF
	printenv |sed -ne 's/^\(no_check_[a-z]\+\)=.*/--\1/pg' |tr _ -
	[ -n "$1" ] && exit "$1" || exit
}

TEMP=`getopt -n $PROG -o h -l no-check-,$(printenv |sed -ne 's/^\(no_check_[a-z]\+\)=.*/\1/pg' |tr _ - |xargs echo |tr ' ' ','),help -- "$@"` || Usage
eval set -- "$TEMP"

while :; do
	case "$1" in
		--no-check-) Usage
			;;
		--no-check-[a-z]*)
			arg="no_check_${1##--no-check-}"
			eval $arg=1
			shift
			;;
		-h|--help) Usage 0
			;;
		--) shift; break
			;;
		*) Fatal "unrecognized option: $1"
			;;
	esac
done

# At least one argument, please.
[ "$#" -ge 1 ] || Usage

check "$@"
