#!/bin/sh -efu

rpm_summary="${rpm_summary?RPM summary required}"

# check for valid summary
check_summary()
{
	local f="$1" && shift || return 1

	if ! printf %s "$rpm_summary" |egrep -qs '[[:alpha:]]'; then
		FileError "invalid SUMMARY: $rpm_summary" "$f"
		return 1
	fi
	return 0
}

run_check() {
	if ! check_summary "$1"; then
		CheckError 'invalid package summary'
		return 1
	fi
}
