#!/bin/sh -efu

bad_deps='fileutils
sh-utils
textutils
XFree86-.*
initscripts
/etc/rc\.d/init\.d\((daemon|killproc|pidof)\)
/etc/init\.d\(.*\)
/usr/sbin/install_info
/usr/sbin/uninstall_info
/sbin/post_ldconfig
/sbin/postun_ldconfig
pam_stack\.so'

bad_prereqs='/sbin/install-info
/sbin/ldconfig'

# check for unacceptable dependencies
check_deps()
{
	local f="$1" && shift || return 1
	local rc=0
	local bad

	local rpm_deps
	rpm_deps=$(printf '%s\n%s\n%s\n%s\n' "$rpm_requires" "$rpm_provides" "$rpm_obsoletes" "$rpm_conflicts")

	if bad=$(printf %s "$rpm_deps" |grep '[$%]'); then
		FileError "invalid dependencies: $(oneliner "$bad")" "$f"
		rc=1
	fi

	if bad=$(printf %s "$rpm_requires" |cut -d' ' -f1 |egrep -x "$bad_deps"); then
		FileError "forbidden requires: $(oneliner "$bad")" "$f"
		rc=1
	fi

	# 2^6: RPMSENSE_PREREQ
	# 2^14: RPMSENSE_FIND_REQUIRES
	bad=$(printf %s "$rpm_requires" |
		awk '$2>=64 && $2!=16384 {print $1}' |
		egrep -x "$bad_prereqs" |
		sort -u)
	if [ -n "$bad" ]; then
		FileError "forbidden prerequires: $(oneliner "$bad")" "$f"
		rc=1
	fi

	[ -n "${rpm_name##kernel-*}" ] ||
		return $rc

	if bad=$(printf %s "$rpm_deps" |cut -d' ' -f1 |egrep '^kernel-(image|modules)'); then
		FileError "forbidden dependencies: $(oneliner "$bad")" "$f"
		rc=1
	fi

	return $rc
}

run_check() {
	if ! check_deps "$1"; then
		CheckError 'package dependencies violation'
		return 1
	fi
}
