#!/bin/sh -efu

rpm_name="${rpm_name?RPM name required}"
rpm_filenames="${rpm_filenames?RPM file list required}"

# check locales not included into glibc-locales
check_locales()
{
	local f="$1" && shift || return 1

	# Do not check glibc-locales package.
	[ "$rpm_name" != glibc-locales ] || return 0

	local locales
	if locales="$(printf %s "$rpm_filenames" |grep '^/usr/share/locale\(/[^/]\+\)\?$')"; then
		FileError "files may belong to glibc-locales only: $(oneliner "$locales")" "$f"
		return 1
	fi
}

run_check() {
	if ! check_locales "$1"; then
		CheckError 'locale subdirectories violation'
		return 1
	fi
}
