#!/bin/sh -efu

check_pkgconfig()
{
	local f="$1"; shift || return

	local bad_dirs
	case ${rpm_arch:?} in
		noarch)
			bad_dirs='^/usr/(lib|lib64)/pkgconfig/' ;;
		i?86|pentium*|athlon*)
			bad_dirs='^/usr/lib64/pkgconfig/' ;;
		x86_64|amd64)
			bad_dirs='^/usr/lib/pkgconfig/' ;;
		*)
			return ;;
	esac

	local bad_files
	if bad_files=$(printf '%s\n' "$rpm_filenames" |egrep "$bad_dirs"); then
		FileError "invalid $rpm_arch pkg-config path: $(printf %s "$bad_files" |tr -s '[:space:]' ' ')" "$f"
		return 1
	fi
}

run_check()
{
	if ! check_pkgconfig "$1"; then
		Message 'ERROR: you have problems with pkg-config files'
		return 1
	fi
}
