#!/bin/sh -efu

rpm_filelist="${rpm_filelist?RPM file list required}"

# check files intersections with known packages
check_libtool()
{
	local f="$1" && shift || return 1
	local rc=0
	local bad

	if bad="$(printf %s "$rpm_filelist" |egrep -e '^(/usr(/X11R6)?)?/lib(64)?/lib[^/]+\.la$')"; then
		FileError "forbidden libtool files: $(printf %s "$bad" |tr -s '[:space:]' ' ')" "$f"
		rc=1
	fi

	return $rc
}

run_check() {
	return 0 # Check disabled for a while

	if ! check_libtool "$1"; then
		Message 'ERROR: you have problems with libtool files'
		return 1
	fi
}
